# -*- org-confirm-babel-evaluate: nil -*-
#+TITLE: generate_supplementals
#+EXPORT_FILE_NAME: tmp
#+INCLUDE: "../project.org::*Header"

* File Information                                                 :noexport:
This file generates supporting documentation for the schematic and gerbers.

* File Usage                                                       :noexport:
1. Setup dependencies using direnv and Guix
2. In Kicad, save the following documentation files (all paths relative to
   project directory):
   - Plot all pages of schematic in color to ./schematic/ in pdf format.
   - Generate bill of materials with blank on Bill of Material command line.
   - Plot gerbers for all important layers to ./gerbers/ in gerber format.
     Plot footprint values. Plot footprint references. Exclude PCB edge layer
     from other layers. Exclude pads from silkscreen. Use Protel filename
     extensions. Subtract soldermask from silkscreen. 4.6, unit mm.
   - Generate drill file to ./gerbers/ in Excellon format. PTH and NPTH in
     single file. Use route command. Absolute drill origin. Drill units
     Inches. Keep zeros.
   - Generate map file in gerber format.
   - Fabrication Outputs: Footprint Position File - gerbers/ output directory,
     CSV format, Inches units, single file for board.
   - Export SVG, F.SilkS and B.SilkS, Color, Board area only, Print board
     edges, One file per layer, to ./gerbers/
3. Take photos of assembled circuit board:
   - Take photo of top of board and save it to images/top.png
   - Take photo of bottom of board and save it to images/bottom.png
4. Export this file to Org as an Org file to expand the macros and evaluate
   the source blocks.

* File Data                                                        :noexport:

#+TBLNAME: repository-info
| {{{name}}}    |
| {{{version}}} |

* Schematic                                                        :noexport:

#+BEGIN_SRC sh :exports results :results output silent

rm -rf ../schematic/images/
mkdir ../schematic/images
convert ../schematic/*.pdf -font Liberation-Sans -density 300 -depth 8 -quality 85 ../schematic/images/schematic%02d.png

#+END_SRC

* Gerbers                                                          :noexport:

#+BEGIN_SRC sh :exports results :results output silent

rm -rf ../gerbers/images/
mkdir ../gerbers/images
inkscape ../gerbers/*.svg --export-dpi=300 --export-type="png"
mv ../gerbers/*.png ../gerbers/images/

#+END_SRC

* Bill of Materials                                                :noexport:

#+BEGIN_SRC python :exports results

from kicad_bom import KicadBom
kb = KicadBom('../')
kb.save_all_csv_files()

#+END_SRC

* Manufacturing Archive                                            :noexport:

#+HEADER: :var name=repository-info[0,0]
#+HEADER: :var version=repository-info[1,0]
#+BEGIN_SRC sh :exports results :results output silent

rm -rf ../manufacturing
mkdir -p ../manufacturing
ZIP_FILENAME=../manufacturing/${name}_v${version}.zip
zip $ZIP_FILENAME ../gerbers/*.g* ../gerbers/*.drl ../gerbers/*.pos ../bom/bom.csv -q

#+END_SRC
