# -*- org-confirm-babel-evaluate: nil -*-
#+TITLE: schematic_gerbers_documentation
#+INCLUDE: "../project.org::*Header"

* File Information                                                 :noexport:
  This file generates supporting documentation for the schematic and gerbers.

* File Usage                                                       :noexport:
  1. Install dependencies:
     - imagemagik
       #+BEGIN_SRC sh :exports none
         sudo apt-get install imagemagick
       #+END_SRC
  2. In Kicad, save the following documentation files (all paths relative to
     project directory):
     - Plot all pages of schematic in color to ../schematic/ in pdf format.
     - Plot gerbers for all important layers to ../gerbers/ in gerber format, using
       Protel filename extensions.
     - Generate drill file to ../gerbers/ in gerber format.
     - Print F.SilkS and B.SilkS, fit to page, no drill mark, 1 page per layer,
       color, to ../gerbers/ in pdf format.
  3. Take photos of assembled circuit board:
     - Take photo of top of board and save it to ../images/top.png
     - Take photo of bottom of board and save it to ../images/bottom.png
  4. Export this file to any format to expand the macros and evaluate the source
     blocks.

* File Data                                                        :noexport:
  #+TBLNAME: repository-info
  | {{{name}}}    |
  | {{{version}}} |

* Schematic                                                        :noexport:
  #+BEGIN_SRC sh :exports results :results output silent
    rm -rf ../schematic/images/
    mkdir ../schematic/images
    convert -density 300 -depth 8 -quality 85 ../schematic/*.pdf ../schematic/images/schematic%02d.png
  #+END_SRC

* Gerbers                                                          :noexport:
  #+HEADER: :var name=repository-info[0,0]
  #+HEADER: :var version=repository-info[1,0]
  #+BEGIN_SRC sh :exports results :results output silent
    rm ../gerbers/*.zip
    ZIP_FILENAME=../gerbers/${name}_v${version}.zip
    zip $ZIP_FILENAME ../gerbers/*.g* ../gerbers/*.drl -q
  #+END_SRC

  #+BEGIN_SRC sh :exports results :results output silent
    rm -rf ../gerbers/images/
    mkdir ../gerbers/images
    convert -density 300 -depth 8 -quality 85 -rotate "90" ../gerbers/*.pdf ../gerbers/images/gerbers%02d.png
  #+END_SRC
